export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS';
export const MEMBER_LOGIN_RE = 'MEMBER_LOGIN_RE' // 重新登录
export const MEMBER_REGISTER_REQUEST = 'MEMBER_REGISTER_REQUEST';
export const MEMBER_REGISTER_SUCCESS = 'MEMBER_REGISTER_SUCCESS';

export const MEMBER_RECEIVE = 'MEMBER_RECEIVE';

export const ANTHOLOGY_REQUEST = 'ANTHOLOGY_REQUEST';
export const ANTHOLOGY_RECEIVE = 'ANTHOLOGY_RECEIVE';
export const ANTHOLOGY_ADD = 'ANTHOLOGY_ADD';

// 文章相关
export const ARTICLE_ADD = 'ARTICLE_ADD';
export const ARTICLE_REQUEST_SOMEONE = 'ARTICLE_REQUEST_SOMEONE';

export const CONTENT_REQUEST = 'CONTENT_REQUEST';
export const CONTENT_RECEIVE = 'CONTENT_RECEIVE';
export const CONTENT_NEED_FETCH = 'CONTENT_NEED_FETCH';
